### ISSUE TITLE
Install issue: JwtStrategy requires a secret or key

### ISSUE THREAD

**Issue by zilveer** [tonyea/lnpoker#2]
Hi,
I get the following error message when I run `node app.js`:

```
D:\wamp64\www\vamppoker\node-poker\node_modules\passport-jwt\lib\strategy.js:45
        throw new TypeError('JwtStrategy requires a secret or key');
        ^

TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (D:\wamp64\www\vamppoker\node-poker\node_modules\passport-jwt\lib\strategy.js:45:15)
    at module.exports.passport (D:\wamp64\www\vamppoker\node-poker\passport.js:15:5)
    at Object.<anonymous> (D:\wamp64\www\vamppoker\node-poker\app.js:34:22)
```
How does the .env file look like or how can I solve this issue?

I installed everything with `npm install`, but what should I do then? A lot has changed since you did the fork :)

regards

**Comment by tonyea** [comment]
Hey, just updated repo with installation instructions. Let me know how it goes.
